Desktop/Sidney/udemy - curso.net/Curso - ASPNETCOREMVC/MyFinance/MyFinance/MyFinance/Controllers/ContaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFinance.Models;

namespace MyFinance.Controllers
{
    public class ContaController : Controller
    {
        IHttpContextAccessor HttpContextAccessor;

        public ContaController(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            ContaModel objConta = new ContaModel(HttpContextAccessor);
            ViewBag.ListaConta = objConta.ListaConta();
            return View();

        }

        [HttpPost]
        public IActionResult CriarConta(ContaModel formulario)
        {
            if (ModelState.IsValid)
            {
                formulario.HttpContextAccessor = HttpContextAccessor;
                formulario.Insert();
                return RedirectToAction("Index");
            }

            return View();
        }


        [HttpGet]
        public IActionResult CriarConta()
        {
            return View();
        }


        [HttpGet]
        public IActionResult ExcluirConta(int id)
        {
            ContaModel objConta = new ContaModel(HttpContextAccessor);
            objConta.Excluir(id);
            return RedirectToAction("Index");
        }

    }
}

Desktop/Sidney/udemy - curso.net/Curso - ASPNETCOREMVC/MyFinance/MyFinance/MyFinance/Controllers/PlanoContasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFinance.Models;

namespace MyFinance.Controllers
{
    public class PlanoContaController : Controller
    {
        IHttpContextAccessor HttpContextAccessor;

        public PlanoContaController(IHttpContextAccessor httpContextAccessor)
        {
            HttpContextAccessor = httpContextAccessor;
        }

        public IActionResult Index()
        {
            PlanoContasModel objPlanoConta = new PlanoContasModel(HttpContextAccessor);
            ViewBag.ListaPlano = objPlanoConta.ListaPlano();
            return View();
        }

        [HttpPost]
        public IActionResult CriarPlanoConta(PlanoContasModel formulario)
        {
            if (ModelState.IsValid)
            {
                formulario.HttpContextAccessor = HttpContextAccessor;
                formulario.Insert();
                return RedirectToAction("Index");
            }
            return View();
        }


        [HttpGet]
        public IActionResult CriarPlanoConta(int? id)
        {
            if (id != null)
            {
                PlanoContasModel objPlanoConta = new PlanoContasModel(HttpContextAccessor);
                ViewBag.Registro = objPlanoConta.CarregarRegistro(id);
            }
            return View();
        }

        [HttpGet]
        public IActionResult ExcluirPlanoConta(int id)
        {
            PlanoContasModel objPlanoConta = new PlanoContasModel(HttpContextAccessor);
            objPlanoConta.Excluir(id);
            return RedirectToAction("Index");
        }
    }
}

Desktop/Sidney/udemy - curso.net/Curso - ASPNETCOREMVC/MyFinance/MyFinance/MyFinance/Views/PlanoConta/CriarPlanoConta.cshtml
@model PlanoContasModel

@{
    ViewData["Title"] = "CriarPlanoConta";
}

<h2>Criar Plano de Contas</h2> <br />

@{ 
    var vDescricao = "";
    var vTipo = "";
    var vId = 0;

    try
    {
        vId = int.Parse(@ViewBag.Registro.Id.ToString());
        vDescricao = @ViewBag.Registro.Descricao.ToString();
        vTipo = @ViewBag.Registro.tipo.ToString();
    }
    catch { }

    }


<form asp-controller="Conta" asp-action="CriarPlanoConta">
    <input type="hidden" asp-for="Id" value="@vId" />

    <div class="form-group">
        <label>Descrição:</label>
        <input type="text" class="form-control" asp-for="Descricao" value="@vDescricao">
        <span asp-validation-for="Descricao"></span>
    </div>

    <div class="form-group">
        <label for="name">Tipo:</label>
        @{
            if (vTipo == "R")
            {
                <div class="radio"><label><input type="radio" class="form-control" asp-for="tipo" value="R" checked>Receita</label></div>
                <div class="radio"><label><input type="radio" class="form-control" asp-for="tipo" value="D" unchecked>Despesa</label></div>
            }
            else
            {
                <div class="radio"><label><input type="radio" class="form-control" asp-for="tipo" value="R" unchecked>Receita</label></div>
                <div class="radio"><label><input type="radio" class="form-control" asp-for="tipo" value="D" checked>Despesa</label></div>
            }
        }

    </div>

    <button type="submit" class="btn btn-success">Registrar</button>
</form>

Desktop/Sidney/udemy - curso.net/Curso - ASPNETCOREMVC/MyFinance/MyFinance/MyFinance/Views/PlanoConta/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h2>Plano de Contas</h2> <br />

<button type="button" class="btn btn-primary" onclick="CriarPlanoConta()">Criar Conta</button> <br /><br />

<div class="table-responsive-lg">

    <table class="table table-bordered">


        <thead>
            <tr>
                <th>ID</th>
                <th>Descrição</th>
                <th>Tipo</th>
                <th scope="col">Ações</th>
            </tr>
        </thead>

        @{


            foreach (var item in (List<PlanoContasModel>)ViewBag.ListaPlano)
            {
                <tbody>
                    <tr>
                        <td>@item.Id.ToString()</td>
                        <td>@item.Descricao.ToString()</td>
                        <td>@item.tipo.ToString().Replace("R", "Receita").Replace("D", "Despesa")</td>
                        <td>
                            <button type="button" class="btn btn-primary" onclick="Editar(@item.Id.ToString())">Editar</button>
                            <button type="button" class="btn btn-danger" onclick="Excluir(@item.Id.ToString())">Excluir</button>

                        </td>
                    </tr>
                </tbody>

            }
        }

    </table>
</div>


<script>

    function CriarPlanoConta() {

        window.location.href = "../PlanoConta/CriarPlanoConta";
    }

    function Excluir(id_conta) {

        window.location.href = "../PlanoConta/ExcluirPlanoConta/" + id_conta;

    }

    function Editar(id_conta) {

        window.location.href = "../PlanoConta/CriarPlanoConta/" + id_conta;

    }

</script>